{
 "title": "Linux Servers -CRC",
 "tags": [
  "OS",
  "Linux",
  "NJMON",
  "CRC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"CPU_ALL\" with key = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "$host cpu total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "CPU_ALL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Idle%|Sys%|User%|Wait%/" }
     ]
    }
   ]
  },
  {
   "title": "$host run queue",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "PROC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Runnable/" }
     ]
    }
   ]
  },
  {
   "title": "free memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "memfree" }
     ]
    }
   ]
  },
  {
   "title": "free swap",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "swapfree" }
     ]
    }
   ]
  },
  {
   "title": "$host memory nr",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "VM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "=~",
       "value": "/^nr_dirty$|^nr_mapped$|^nr_page_table_pages$|^nr_slab$|^nr_unstable$|^nr_writeback$/"
      }
     ]
    }
   ]
  },
  {
   "title": "$host memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "=~",
       "value": "/^active$|^memtotal$|^cached$|^inactive$/"
      }
     ]
    }
   ]
  },
  {
   "title": "$host memory usage details",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "=~",
       "value": "/^memtotal$|^active$|^memfree$|^memshared$|^buffers$|^cached$|^inactive$/"
      }
     ]
    }
   ]
  },
  {
   "title": "$host swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "=~",
       "value": "/^swaptotal$|^swapcached$|^swapfree$/"
      }
     ]
    }
   ]
  },
  {
   "title": "$host paging details",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "VM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "=~",
       "value": "/pgactivate|pgalloc_dma|pgalloc_high|pgalloc_normal|pgdeactivate|pgfault|pgfree|pginodesteal|pgmajfault|pgpgin|pgpgout|pgrefill_dma|pgrefill_high|pgrefill_normal|pgrotated|pgscan_direct_dma|pgscan_direct_high|pgscan_direct_normal|pgscan_kswapd_dma|pgscan_kswapd_high|pgscan_kswapd_normal|pgsteal_dma|pgsteal_high|pgsteal_normal/"
      }
     ]
    }
   ]
  },
  {
   "title": "$host network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "NET",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/KB/" }
     ]
    }
   ]
  },
  {
   "title": "$host network packet",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "NETPACKET",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host network errors",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "NETERROR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host top processes",
   "type": "graph",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name $tag_command ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "command" ], "type": "tag" }
     ],
     "measurement": "TOP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/%CPU/" }
     ]
    }
   ]
  },
  {
   "title": "Filespace %Used",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "groupByTags": [ "name" ],
     "measurement": "JFSFILE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "transform": "timeseries_to_columns"
    }
   ]
  },
  {
   "title": "$host disk read KB/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "DISKREAD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^sd*/" }
     ]
    }
   ]
  },
  {
   "title": "$host disk write KB/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "DISKWRITE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/sd*/" }
     ]
    }
   ]
  },
  {
   "title": "$host disk transfers per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "DISKXFER",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/sd*/" }
     ]
    }
   ]
  },
  {
   "title": "$host disk busy %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "DISKBUSY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/sd*/" }
     ]
    }
   ]
  }
 ]
}