FROM httpd:latest
LABEL author="CRC Team"
LABEL description="Apache web server"
EXPOSE 8080
COPY conf/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY conf/status.conf /usr/local/apache2/conf/extra/status.conf
