CREATE USER 'exporter'@'exp-mariadb' IDENTIFIED BY 'crc2019' WITH MAX_USER_CONNECTIONS 3;
GRANT RELOAD, PROCESS, REPLICATION SLAVE, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'exp-mariadb';
CREATE USER 'exporter'@'10.200.200.151' IDENTIFIED BY 'crc2019' WITH MAX_USER_CONNECTIONS 3;
GRANT RELOAD, PROCESS, REPLICATION SLAVE, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'10.200.200.151';
flush privileges;
